app: auth-service-cognito
service: auth-service-cognito
frameworkVersion: "3"
useDotenv: true

provider:
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Access-Control-Allow-Origin
        - Access-Control-Allow-Headers
        - Access-Control-Allow-Methods
      allowedMethods:
        - GET
        - POST
        - PUT
  logs:
    httpApi: true

  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
  - Effect: Allow
    Action:
      - cognito-idp:AdminInitiateAuth
      - cognito-idp:AdminCreateUser
      - cognito-idp:AdminSetUserPassword
      - cognito-idp:AdminGetUser
    Resource: '*'
 
  environment:
    CLIENTES_POOL_ID: ${self:custom.CLIENTES_POOL_ID}
    CLIENTES_POOL_CLIENT_ID: ${self:custom.CLIENTES_POOL_CLIENT_ID}
    CLIENTES_IDENTITY_POOL_ID: ${self:custom.CLIENTES_IDENTITY_POOL_ID}

functions:
  signUpUser:
    handler: src/functions/signUp.signUpUser
    events:
      - httpApi:
          path: /api/signup
          method: post

custom:
  serverless-offline:
    httpPort: 3001
  CLIENTES_POOL_ID: ${ssm:/pools/client}
  CLIENTES_POOL_CLIENT_ID: ${ssm:/pools/client/client}
  CLIENTES_IDENTITY_POOL_ID: ${ssm:/pools/identity/client}

plugins:
  - serverless-offline
  - serverless-plugin-typescript
