app: auth-service-cognito
service: auth-service-cognito
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 60
  region: us-east-1
  stage: dev
 
  environment:
    CLIENTES_POOL_ID: ${self:custom.CLIENTES_POOL_ID}
    CLIENTES_POOL_CLIENT_ID: ${self:custom.CLIENTES_POOL_CLIENT_ID}
    CLIENTES_IDENTITY_POOL_ID: ${self:custom.CLIENTES_IDENTITY_POOL_ID}
    ADMIN_POOL_ID: ${self:custom.ADMIN_POOL_ID}
    ADMIN_POOL_CLIENT_ID: ${self:custom.ADMIN_POOL_CLIENT_ID}
    ADMIN_IDENTITY_POOL_ID: ${self:custom.ADMIN_IDENTITY_POOL_ID}


functions:
  authorization:
    handler: src/functions/authorizations/auth.handler
  signUpClient:
    handler: src/functions/signUpClient.handler
    events:
      - httpApi:
          path: /api/signup
          method: post

  signUpAdmin:
    handler: src/functions/signUpAdmin.handler
    events:
      - httpApi:
          path: /api/admin
          method: post
  
  signInClient:
    handler: src/functions/signInClient.handler
    events:
      - httpApi:
          path: /api/client
          method: post
  
  exclusionClient:
    handler: src/functions/exclusionClient.handler
    events:
      - httpApi:
          path: /api/client/exclusion
          method: post

custom:
  serverless-offline:
    httpPort: 3001
  CLIENTES_POOL_ID: ${ssm:/pools/client}
  CLIENTES_POOL_CLIENT_ID: ${ssm:/pools/client/client}
  CLIENTES_IDENTITY_POOL_ID: ${ssm:/pools/identity/client}
  COGNITO_REGION: ${ssm:/pools/identity/region}
  ADMIN_POOL_ID: ${ssm:/pools/admin}
  ADMIN_POOL_CLIENT_ID: ${ssm:/pools/admin/client}
  ADMIN_IDENTITY_POOL_ID: ${ssm:/pools/identity/admin}


plugins:
  - serverless-offline
  - serverless-plugin-typescript
